site_name: docs.clouddocs.ch
site_url: https://docs.clouddocs.ch
site_description: "Documentation for portal.clouddocs.ch."
site_author: paperflakes AG

nav:
  - Configuration:
      - Tenant: Configuration/Tenant.md
      - Client: Configuration/Client.md
      - Sections:
          - Documents: Configuration/Sections/Documents.md
          - Tasks: Configuration/Sections/Tasks.md
          - Uploads: Configuration/Sections/Uploads.md
          - Fields: Configuration/Sections/Fields.md
          - Query: Configuration/Sections/Query.md
      - Translations: Configuration/Translations.md
      - Index: Configuration/Index.md
  - API:
      - API: API/API.md
      - Tenants: API/Tenants.md


theme:
  name: readthedocs
  custom_dir: custom_theme/
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  copyright: "Â© codebar Solutions AG"

markdown_extensions:
  - admonition
  - codehilite

extra_css:
  - hidefooter.css

extra_javascript:
  - js/userback.js

docs_dir: docs
site_dir: site
use_directory_urls: true
